app/app.js
config.html
mediaassets.html

-Created App.js to define the adminUI module and setup controllers for
each page with empty scopes
-Added Angular directive to each page (ngApp) and appropriate
controller directives to each page

Add Angular View/Controllers

---

.gitignore
app/app.js
app/services/lambdaService.js
js/test/initialTest.spec.js
js/test/lambdaServiceTests.spec.js
karma.conf.js
package.json

- Fixes the main app in `app.js` (using Andre's fix)
- Creates a service to make a POST request on a lambda API gateway
- Deleted the old spec.js file, created a proper test file for the lambdaService (run `gulp test` to see)
- Added a way to show code coverage: uses `karma-coverage` to generate a nice report in the `reports/` folder

Feature create lambda service

---

app/views/playlist.html

-Form was submitting twice so everything was uploaded and added to the
playlist twice, removed the ng-submit="upload()" from the form object in the HTML as there is also an ng-click on the submit button
-Moved clearing the upload progress bar to the reset form function so
it’s all done in the same spot
-Unit test still failing because of the response from the S3 object but in the future this will be using the S3 service instead
-Added .htaccess on EC2 host to handle Angular routing, uploaded this
code to test and everything is working as expected

Bug Fixes/General Changes

---

.gitignore
app/app.js
app/controllers/PlaylistController.js
app/index.html
bower.json
karma.conf.js

-Generates UUID for each video on upload
-Unit test still failing because of API mock

Feature generate uuids

---

app/app.js
app/controllers/PlaylistController.js
app/services/S3Service.js
app/views/playlist.html

Features
======
- Thumbnail is generated at halfway point
- Duration is generated
- First video start time is put at 24 hours after upload (for now)
- Videos now upload successfully
Issues
=====
- After one video is uploaded, the form will close midway through uploading any other video, then alert the user later when it is ACTUALLY done uploading
- When that happens and a third video needs to be uploaded, the progress bar is set to 100%
- Something is happening with some async issues, but it at least uploads now
- Start time needs to be in 24 hour format
Possible Fixes
=========
- S3 service's upload function could simply be put back into PlaylistController, but this defeats the purpose (albeit, will fix the upload bugs)

Fixes bugs, adds new features

---

app/controllers/PlaylistController.js
app/services/S3Service.js
app/services/schedulerService.js
app/views/playlist.html

Features
=======
- On reorder/delete, start time is dynamically updated
- If the user is adding the first video to a playlist, the user is given a list of options for the start time
- Handles if a user uploads multiple videos with the same title
- Uploads synchronously 
- Alerts user upload is in progress (in case of hang or slow network performance)
- Some bug fixes
- When a video is going to be added, the form's fields have default values (and correctly pass these defaults)
- Form correctly resets
Issues
======
- ~~For now, all S3 uploads are back in the hands of `PlaylistController.js` rather than `S3Service.js`. It ensures a 100% synchronous process~~
- ~~Once the asynchronous issues are fixed in `S3Service.js` then the methods can be uncommented~~
- `S3Service.js` issues fixed, the …

Add big update to playlist UI

---

app/controllers/PlaylistController.js
app/index.html
app/services/BXFGeneratorService.js
app/services/lambdaService.js
app/views/playlist.html
package.json
server.js

-Pull request to merge conflicts in to separate branch only, will open another pull request after conflicts are merged, no review required yet

Add JSON to BXF, Publish button

---

app/controllers/ConfigController.js
app/services/schedulerService.js
app/views/config.html

Added AdminUI Config feature with a persistence implementation similar to the playlist schedule (storing data in service variables) with the difference of the addition of a 'save' button on the view and a save function in the controller.

Modified ConfigController, config.html view, and schedulerService for the initial version of the AdminUI config feature

---

app/controllers/MediaAssetsController.js
app/controllers/PlaylistController.js
app/index.html
app/services/S3Service.js
app/services/mediaAssetsService.js
app/views/mediaassets.html

Can now view assets uploaded to S3

Media assets complete

---

app/controllers/LiveStreamController.js
app/index.html
app/views/livestream.html
package.json

Features
======
- Autoplays the video
- Autosizes the video
- Has media controls for controlling playback
Issues
====
- None discovered
Make sure to run `npm install` so the new packages are installed

Add LiveStream capabilities

---

app/views/livestream.html

Forgot to add this commit in my last PR. This just makes the video player a little more responsive depending on window size

Have video player fit window a little nicer

---

app/controllers/ConfigController.js
app/services/schedulerService.js
app/views/config.html

Added more Config Options and Inputs, changed options array to a JSON object.
Added Schedule Name and several Channel config options.
To Do:
-Maybe add headers/ group the options.
-Input for channel number is disabled, need to design a way to input the
channel number. (will try form groups, number input type and ng-change
with a function to create the string from the numbers)

More AdminUIConfig Options branch merge

---

app/controllers/ConfigController.js
app/services/BXFGeneratorService.js
app/services/schedulerService.js
app/views/config.html
js/test/BXFGeneratorServiceTests.spec.js
js/test/configControllerTests.spec.js
js/test/schedulerServiceTests.spec.js

Pretty much reverting some of the added options from previous commits, tweaking the bxfGenerator to use default values for the removed options and modifying expected values for the tests.

Feature config update

---

app/controllers/PlaylistController.js
app/index.html
app/services/S3Service.js
app/services/currentVideoStatusService.js
app/services/mediaProcessingService.js
bower.json
js/test/MediaAssetsControllerTests.spec.js
js/test/PlaylistControllerTests.spec.js
js/test/mediaAssetsServiceTests.spec.js
js/test/mediaProcessingServiceTests.spec.js
karma.conf.js

Features
======
- `PlaylistController.js` has been refactored
- All media processing functions are moved to a new service: `mediaProcessingService.js`
- Size of the file has been significantly reduced
- Most of `PlaylistController` is now covered in tests
- Figured out how to mock out a service's function calls (see the `checkLiveStatus() tests` on line 491 of the test file for `PlaylistController`
Issues
====
- None

Refactor PlaylistController, mock out some tests

---

app/services/S3Service.js

-Now uses AWS Cognito for identity management (S3 authentication)

Change AWS SDK to use AWS Cognito

---

app/controllers/LiveStreamController.js
app/controllers/MediaAssetsController.js
app/controllers/PlaylistController.js
app/services/S3Service.js
app/services/lambdaService.js
app/services/schedulerService.js
app/views/mediaassets.html
app/views/playlist.html
clientapp/app.js
clientapp/controllers/ClientLiveStreamController.js
js/test/PlaylistControllerTests.spec.js
js/test/schedulerServiceTests.spec.js

Bug Fixes
=======
- Drag and drop correctly locks videos in place
- Removing videos and reordering videos correctly sets order
- Inserting videos into specific order works
- Default time set for "Now"
- Both modal forms correctly filter the order to insert in
- Small bug fixes
- Fix tests
- AWS Cognito now works (thanks to @cjuszczak)

Fix bugs and credentials

---

app/services/lambdaService.js
js/test/PlaylistControllerTests.spec.js
js/test/lambdaServiceTests.spec.js
js/test/mediaProcessingServiceTests.spec.js

Added the URL via `schedulerService`, fixed tests as well

Adds the other URL to lambdaService

---

app/controllers/LiveStreamController.js
app/controllers/MediaAssetsController.js
app/controllers/PlaylistController.js
app/services/BXFGeneratorService.js
app/services/S3Service.js
app/services/lambdaService.js
app/services/schedulerService.js
app/views/livestream.html
app/views/mediaassets.html
app/views/playlist.html
clientapp/controllers/ClientLiveStreamController.js
clientapp/index.html
clientapp/views/livestream.html
js/test/PlaylistControllerTests.spec.js
js/test/clientLiveStreamControllerTest.spec.js

Fixes
====
- Some videos weren't remaining locked,  
- Livestream works correctly now
- Publishing has been fixed
- Order will just default to end of the playlist, if a user wants to switch the order they can just drag and drop
TODO
====
- Implement Reset button, will be done in separate branch. Until this, this fixes critical bugs

Fix major bugs

---

app/css/bootstrap.css
app/css/dashboard.css
app/index.html
app/views/mediaassets.html
clientapp/css/dashboard.css
clientapp/index.html

-Made ClientUI use the whole window versus the right bottom 2/3rds
-Fixed collapse nav button on mobile sized screens
-Rearranged buttons on Media Assets page to be in the same positions as the Playlist page
-Changed the color and added a glyphicon to the Refresh button on the Media Assets page to match Playlist page

Minor ui changes

---

app/controllers/MediaAssetsController.js
app/controllers/PlaylistController.js
app/services/S3Service.js
app/services/schedulerService.js
app/views/playlist.html
js/test/MediaAssetsControllerTests.spec.js
js/test/PlaylistControllerTests.spec.js
js/test/S3ServiceTest.spec.js

Features
======
- Reset button clears the playlist (if nothing is locked)
Notes
====
- Some functionality needed to be moved to `schedulerService` to ensure data bindings remained consistent across views

Add reset button

---

app/controllers/PlaylistController.js
app/services/lambdaService.js
js/test/PlaylistControllerTests.spec.js
js/test/mediaProcessingServiceTests.spec.js

Comment out BXF Sent Successfully message for now

Comment out toastr message
